# Database Settings
db_host = db
db_port = 5432
db_user = judge0
db_password = judge0password
db_name = judge0

# Redis Settings
redis_host = redis
redis_port = 6379

# Sandbox limitations (Optional overrides)
# max_cpu_time = 5.0
# max_real_time = 15.0
# max_memory = 262144
# max_stack = 65536
# max_process_limit = 120
# max_file_size = 10240
